### ISSUE TITLE
Upgrade?

### ISSUE THREAD

**Issue by ghost** [jellyfishcoder/OhMyFish#1]
Hi @jellyfishcoder  
I'm no longer maintaining omf, and would appreciate a ton if you can upgrade to [fisherman](https://github.com/fisherman/fisherman):
- Why? fisherman/fisherman#69 (comment)

Everything, including legacy plugins/themes work great with fisherman, but new content is no longer compat. with oh-my-fish.

**Comment by jellyfishcoder** [comment]
Ok, thanks.

**Comment by ghost** [comment]
Thanks, cheers! :)
